### ISSUE TITLE
[Queue] Manual queue generator

### ISSUE THREAD

**Issue by Chiniga** [Chiniga/pa-queue-ph#36]
Add manual queue generation for custom games

**Comment by valkeriemao** [comment]
Issue: Manually generated queue is not activated when Queue list was empty beforehand.

Pre-req:
6 or more players

Steps:
1. Select 4 players from Player list.
2. Tap on Generate Queue.
3. Go to Queue.
4. Check the created queue.

**Comment by Chiniga** [comment]
Issue resolved. Please re-check.
