### ISSUE TITLE
Additional queues are created when creating a single manual queue

### ISSUE THREAD

**Issue by valkeriemao** [Chiniga/pa-queue-ph#95]
Pre-req: 
Players list have 8 or more players.
Player levels are balanced for 2 queues to be produced (ie. All players are at level 3).
Court number is 1.
Queue list is empty.

Replication:
Create a manual queue from Player list.
Check Queue list.

Question: Is this behavior expected?

**Comment by Chiniga** [comment]
No, it is not. Will create a bug fix for this

**Comment by valkeriemao** [comment]
Passed
